workflows:
  my-workflow:
    name: Build Ios Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/Runner.ipa
