// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbGg2CpLz-URvWnSqkud_tw8DoUx_pLyw',
    appId: '1:606411572487:web:4e76408d70f8ffbe3c31a2',
    messagingSenderId: '606411572487',
    projectId: 'epresensi-410114',
    authDomain: 'epresensi-410114.firebaseapp.com',
    storageBucket: 'epresensi-410114.appspot.com',
    measurementId: 'G-0M81S9VG6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRlF5xi_4vQkPbQm1k1gZvnT8jF35oOgY',
    appId: '1:606411572487:android:af715ce009329a7d3c31a2',
    messagingSenderId: '606411572487',
    projectId: 'epresensi-410114',
    storageBucket: 'epresensi-410114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDexQClxnT6C65XvVd673zWWjOybz63m-w',
    appId: '1:606411572487:ios:af3353139307164f3c31a2',
    messagingSenderId: '606411572487',
    projectId: 'epresensi-410114',
    storageBucket: 'epresensi-410114.appspot.com',
    iosBundleId: 'com.bocahgabut.eAbsensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDexQClxnT6C65XvVd673zWWjOybz63m-w',
    appId: '1:606411572487:ios:cb6598b1d684f26b3c31a2',
    messagingSenderId: '606411572487',
    projectId: 'epresensi-410114',
    storageBucket: 'epresensi-410114.appspot.com',
    iosBundleId: 'com.bocahgabut.eAbsensi.RunnerTests',
  );
}
